"""add login lockout fields

Revision ID: 1443ddeb6213
Revises: 092f57a4a368
Create Date: 2025-04-02 18:02:38.171408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1443ddeb6213'
down_revision = '092f57a4a368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
