"""add timestamp to sightings

Revision ID: e8988a979a1c
Revises: 8f3c13a304d7
Create Date: 2025-03-20 11:11:58.698072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8988a979a1c'
down_revision = '8f3c13a304d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
